# Generated by Django 3.1.7 on 2022-03-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_category',
            field=models.BooleanField(default=True, editable=False, verbose_name='Upload/Categoria'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Upload/Images', verbose_name='Imagem'),
        ),
    ]
