# Generated by Django 3.1.7 on 2022-03-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220324_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='Upload/Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_category',
            field=models.BooleanField(default=True, editable=False, verbose_name='is_categoria'),
        ),
    ]
